#pragma once

enum class PRIORITY { LOW, NORMAL, HIGH };
enum class DEMAND { LOW, NORMAL, HIGH };
enum class DATE_TYPE { ANYTIME, BEFORE, AT, AFTER };
enum class RANK_TYPE { ANYWHERE, BEFORE, AFTER };
enum class WEEKDAY { SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY };
enum class TASK_COLLITION { NONE, MOVE_NEW, MOVE_OLD };

enum ARGUMENT_MODE { NONE, ARG_DATE, CONTAINS_TAGS, CONTAINS_ALL_TAGS, NO_TAGS, REG_TEXT, REG_TEXT_CONTENT, VERSIONS };
enum OPEN_MODE { HTML, MARKDOWN, LATEX, PDF, DOCX };
enum FOLDER_WATCHER_MODE { READ_NONE, READ_FOLDER, READ_TAGS };
enum ALIGN { LEFT, MIDDLE, RIGHT };

enum class CMD { NEW, FIND, FILTER, SHOW, ADD_DATA, DETAILS, TAGS, QUIT, CREATE_MODE, DELETE_MODE, EDIT_MODE, ACTIVATE, DEACTIVATE, MODES, UPDATE, OPEN, HELP, TODOS, ADD_TASK, REMOVE_TASK, EDIT_TASK, SHOW_TASKS };
enum class PA { DATE, TAGS, MODE_NAME, CMD, TASK_NAME };

// dont forget to add data fields to the OA_DATA set in utils.cpp
enum class OA { DATA, DATE_R, CTAGS, CATAGS, NTAGS, REGT, REGC, VERS_R, STAGS, MDATA, TOC, NODATE, IMG, HTML, TEX, PDF, DOCX, MD, PATH, LPATH, LMOD, CONTENT, ADDOPT, REMOPT, ADDTAG, REMTAG, CHANAME, TAGS, DATES, REGTEXT, VERSIONS, NAME, CMD, STAGS_ARG, MDATA_ARG, TOC_ARG, NODATE_ARG, IMG_ARG, HTML_ARG, TEX_ARG, PDF_ARG, DOCX_ARG, MD_ARG, PATH_ARG, LPATH_ARG, LMOD_ARG, CONTENT_ARG, ADDWF, REMWF, PATHANDTAGS, PATHD, SHEAD, SIMG, SLINK, TASKNAME, TASKID_ARG, TASKID, TASKPRIORITIY_ARG, PRIORITY, TASKDEMAND_ARG, DEMAND, TASKDURATION_ARG, DURATION };

enum CONV_ERROR { CONV_SUCCESS, CONV_OVERFLOW, CONV_UNDERFLOW, CONV_INCONVERTIBLE };